# Generated by Django 6.0.4 on 2026-06-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
